CFG_VIT = {
    'model' : {'name': 'transformers.ViTForImageClassification',
               'weight': 'google/vit-base-patch16-224',
               'img_size' : 224,
               'num_classes' : 11014,
               'scale' : 50,
               'margin' : 0.9},
    'training' : {'batch_size':64,
                  'epochs' :30,
                  'optim' : 'torch.optim.AdamW',
                  'lr_scheduler': 'torch.optim.lr_scheduler.CosineAnnealingWarmRestarts',
                  'backbone_lr':2e-5,
                  'arcface_lr':2e-3,
                  'T_mult':1,
                  'T_0':643,
                  'T_up':1500,
                  'eta_min':1e-7,
                  'gamma':0.9},
    'path' : {'output' : '../output/image_encoder/',
              'df' : '../data/train.csv',
              'image_dir' : '../data/'}
}

CFG_BERT = {
    'model' : {'name': 'transformers.BertModel',
               'weight': 'cahya/bert-base-indonesian-522M',
               'max_length': 256,
               'num_classes':11014,
               'scale' : 50,
               'margin' : 0.7},
    'training' : {'batch_size' : 32,
                  'epochs':30,
                  'optim' : 'torch.optim.AdamW',
                  'lr_scheduler' : 'torch.optim.lr_scheduler.CosineAnnealingWarmRestarts',
                  'backbone_lr':1e-5,
                  'arcface_lr':5e-3,
                  'T_0':643,
                  'T_mult':1,
                  'T_up': 1500,
                  'eta_min':1e-7,
                  'gamma':0.9},
    'path' : {'output': '../output/text_encoder/',
              'df' : '../data/train.csv'}
    }
